name: Alert on feature push

on:
  push:
    branches:
      - 'feature'

jobs:
  job_name: 
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: feature branch push listener
        run: echo 'hi git actions'
